name: Tests for build-push-action
on:
  workflow_dispatch:

jobs:
  actions-tests:
    name: Perform test
    runs-on:
      - nscloud-ubuntu-22.04-amd64-1x2
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

