name: Tests for build-push-action
on:
  workflow_dispatch:

jobs:
  test-without-init:
    name: Perform test without init
    runs-on:
      - nscloud-ubuntu-22.04-amd64-1x2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false


  test-with-init:
    name: Perform test with init
    if: false
    runs-on:
      - nscloud-ubuntu-22.04-amd64-1x2
      - nscloud-exp-features:use-init
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false


  test-2:
    name: Perform test without init crazy
    runs-on:
      - nscloud-ubuntu-22.04-amd64-1x2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
      - name: Make docker run fail
        run: sudo mv /usr/bin/docker /usr/bin/dockerorig && sudo cp dockershim /usr/bin/docker
      - name: Check result
        run: docker version